SELECT DISTINCT *
WHERE {
  ?id foaf:name ?v0.
  OPTIONAL { ?id foaf:depiction ?v1 }.
  OPTIONAL { ?id schema:birthDate ?v2 }.
  OPTIONAL { ?id schema:deathDate ?v3 }.

  ?id a ecrm:E21_Person.
  [] ecrm:P14_carried_out_by ?id
}
LIMIT 10
